### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by gachiemchiep** [intel/ros2_grasp_library#80]
Hello 
Thank you for your contribution

When compiling ros2_grasp_library, I occurred the following error 

```bash
[32.086s] WARNING:colcon.colcon_cmake.task.cmake.build:Could not build CMake package 'recognize_pick' because the CMake cache has no 'CMAKE_PROJECT_NAME' variable
--- stderr: recognize_pick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 65, in build
    has_install_target = await has_target(args.build_base, 'install')
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 57, in has_target
    return target in await get_makefile_targets(path)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 78, in get_makefile_targets
    CMAKE_EXECUTABLE, '--build', path, '--target', 'help'], cwd=path)
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['/usr/local/bin/cmake', '--build', '/datadrive/workspace/ros2_ws/build/recognize_pick', '--target', 'help'] to pass: Error: could not find CMAKE_PROJECT_NAME in Cache

---
Failed   <<< recognize_pick [0.11s, exited with code 1]
Aborted  <<< random_pick [1.56s]                                                                                                                                  
Aborted  <<< handeye_tf_service [17.9s]                                                                                                                            
Aborted  <<< draw_x [9.56s]                                                                                                                                         
Aborted  <<< fixed_position_pick [9.55s]
Aborted  <<< grasp_ros2 [8.69s]                                                                                        
Aborted  <<< handeye_target_detection [22.9s]                                    
                                   
Summary: 20 packages finished [40.8s]
  1 package failed: recognize_pick
  6 packages aborted: draw_x fixed_position_pick grasp_ros2 handeye_target_detection handeye_tf_service random_pick
  3 packages had stderr output: grasp_ros2 handeye_target_detection recognize_pick
Expected ['/usr/local/bin/cmake', '--build', '/datadrive/workspace/ros2_ws/build/recognize_pick', '--target', 'help'] to pass: Error: could not find CMAKE_PROJECT_NAME in Cache

```

Do you guys know how to fix this?
Thanks

**Comment by mattijsk14** [comment]
Dear @gachiemchiep ,

Did you already figured out how to solve this error?

Thanks in advance!!

**Comment by gachiemchiep** [comment]
@mattijsk14 
No I haven't figure out yet.
